const dictionaryMonthNames: Map<string, number> = new Map()
dictionaryMonthNames.set("enero", 1)
dictionaryMonthNames.set("febrero", 2)
dictionaryMonthNames.set("marzo", 3)
dictionaryMonthNames.set("abril", 4)
dictionaryMonthNames.set("mayo", 5)
dictionaryMonthNames.set("junio", 6)
dictionaryMonthNames.set("julio", 7)
dictionaryMonthNames.set("agosto", 8)
dictionaryMonthNames.set("septiembre", 9)
dictionaryMonthNames.set("octubre", 10)
dictionaryMonthNames.set("noviembre", 11)
dictionaryMonthNames.set("diciembre", 12)

dictionaryMonthNames.set("january", 1)
dictionaryMonthNames.set("february", 2)
dictionaryMonthNames.set("march", 3)
dictionaryMonthNames.set("april", 4)
dictionaryMonthNames.set("may", 5)
dictionaryMonthNames.set("june", 6)
dictionaryMonthNames.set("july", 7)
dictionaryMonthNames.set("august", 8)
dictionaryMonthNames.set("september", 9)
dictionaryMonthNames.set("october", 10)
dictionaryMonthNames.set("november", 11)
dictionaryMonthNames.set("december", 12)
export {
  dictionaryMonthNames
}
